# Generated by Django 5.2.14 on 2026-05-11 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fifa_code', models.CharField(max_length=3, unique=True)),
                ('flag_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('group_stage', 'Group Stage'), ('knockout', 'Knockout'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('num_groups', models.PositiveIntegerField(default=12)),
                ('teams_per_group', models.PositiveIntegerField(default=4)),
                ('third_place_advancers', models.PositiveIntegerField(default=8)),
                ('scoring_config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('r32', 'Round of 32'), ('r16', 'Round of 16'), ('qf', 'Quarter-Final'), ('sf', 'Semi-Final'), ('third_place', 'Third Place'), ('final', 'Final')], max_length=20)),
                ('group_letter', models.CharField(blank=True, max_length=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tournaments.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tournaments.team')),
                ('knockout_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_wins', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament', 'stage', 'group_letter'], name='tournaments_tournam_ca2fb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_letter', models.CharField(max_length=1)),
                ('fifa_ranking', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
