# Generated by Django 5.2.14 on 2026-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_knockout_placeholder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='conduct_score',
            field=models.IntegerField(default=0),
        ),
    ]
