# Generated by Django 5.2.14 on 2026-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentteam_conduct_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
