# Generated by Django 5.2.14 on 2026-05-11 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('completed', 'Completed')], default='open', max_length=20)),
                ('lock_deadline', models.DateTimeField(blank=True, null=True)),
                ('scoring_config', models.JSONField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='pools.pool')),
            ],
            options={
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PoolChampionPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_picks', to='pools.pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champion_picks', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('predictions_submitted', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pools.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PoolTopScorerPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer_picks', to='pools.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_home_score', models.PositiveIntegerField()),
                ('predicted_away_score', models.PositiveIntegerField()),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tournaments.match')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pools.pool')),
                ('predicted_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_wins', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool', 'match')},
            },
        ),
    ]
