# Generated by Django 5.2.14 on 2026-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='previous_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
