# Generated by Django 5.2.14 on 2026-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_thirdplacetiebreakerpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='advancement_bonus_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='group_classification_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
