# Generated by Django 5.2.14 on 2026-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_leaderboardentry_advancement_bonus_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='invite_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
